In [32]:
import pandas as pd
import numpy as np

### Ratings where there are clear themes, fighting vs non fighting

In [2]:
df = pd.read_csv('arcade.csv')
df.drop(df.columns[0], axis=1, inplace=True)
df.drop(df.columns[-1], axis=1, inplace=True)
df.drop(11, inplace=True)

In [33]:
from scipy.sparse.linalg import svds
from scipy import dot
df_matrix = df.as_matrix()
#df_matrix.asfp
df_matrix = df_matrix.astype(float)

### Try k=2

In [4]:
U, sigma1, Vt = svds(df_matrix, k = 2)
sigma = np.diag(sigma1)
print 'here is our user:concept matrix'
print U
print 'concept:concept matrix'
print sigma
print 'game : concept matrix'
print Vt

here is our user:concept matrix
[[  2.41958809e-16   3.97460296e-01]
 [  1.59511184e-16   4.71687338e-01]
 [  2.07584959e-16   4.75932015e-01]
 [  2.03942302e-16   5.26455196e-01]
 [  5.23258928e-18   3.25713730e-01]
 [  1.58425755e-17   9.88968044e-02]
 [  4.62535267e-01  -6.44723040e-17]
 [  4.36477710e-01  -7.77677912e-17]
 [  3.95666473e-01  -5.39270886e-17]
 [  3.23599888e-01  -5.50546802e-17]
 [  5.78169084e-01  -8.05903801e-17]]
concept:concept matrix
[[ 11.48800728   0.        ]
 [  0.          12.7376689 ]]
game : concept matrix
[[ -4.18468760e-17   4.54999055e-17   5.10425006e-16   5.84898554e-01
    7.43503575e-01   3.24185310e-01]
 [  6.43547553e-01   3.14928687e-01   6.97614843e-01  -6.50530579e-17
   -1.40253658e-16  -7.23280218e-17]]

### When we set k=2, can see there are 2 clear camps. Fighting vs non fighting. 

### The U and Vt matrix had literally no overlap. 

### What happens if our fighting games fans give non-fighting some 1 rating?

In [5]:
df_matrix[0][-1] = 1
df_matrix[1][-2] = 1
df_matrix[-1][-2] = 0
#Now, our fighting games fans have rated puppies with some 1 star ratings. 
# Lets see what happens to our sVD
df_matrix

array([[ 0.,  5.,  5.,  0.,  0.,  1.],
       [ 5.,  0.,  4.,  0.,  1.,  0.],
       [ 4.,  0.,  5.,  0.,  0.,  0.],
       [ 5.,  0.,  5.,  0.,  0.,  0.],
       [ 4.,  5.,  0.,  0.,  0.,  0.],
       [ 0.,  4.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  4.,  4.,  0.],
       [ 0.,  0.,  0.,  0.,  5.,  4.],
       [ 0.,  0.,  0.,  5.,  0.,  5.],
       [ 0.,  0.,  0.,  0.,  5.,  0.],
       [ 0.,  0.,  0.,  5.,  0.,  0.]])

In [6]:
U, sigma1, Vt = svds(df_matrix, k = 2)
sigma = np.diag(sigma1)
print 'here is our user:concept matrix'
print U
print 'concept:concept matrix'
print sigma
print 'game : concept matrix'
print Vt

here is our user:concept matrix
[[-0.00899396 -0.39949882]
 [ 0.00190064 -0.47405883]
 [ 0.05986777 -0.47213389]
 [ 0.06731112 -0.52219736]
 [ 0.03866235 -0.32311518]
 [ 0.00711117 -0.09828904]
 [-0.49469421 -0.03396641]
 [-0.48886718 -0.05021746]
 [-0.56129621 -0.03505828]
 [-0.29695801 -0.03118736]
 [-0.32140975 -0.01127066]]
concept:concept matrix
[[  9.97204615   0.        ]
 [  0.          12.76865604]]
game : concept matrix
[[ 0.07422541  0.01772822  0.0600205  -0.64102257 -0.5922558  -0.47843178]
 [-0.63924325 -0.31375472 -0.69430844 -0.02878222 -0.07964414 -0.0607472 ]]

In [7]:
dot(U, sigma)

array([[-0.08968819, -5.10106302],
       [ 0.01895326, -6.05309416],
       [ 0.59700415, -6.02851521],
       [ 0.67122956, -6.66775846],
       [ 0.38554275, -4.12574664],
       [ 0.07091287, -1.2550189 ],
       [-4.93311349, -0.43370544],
       [-4.87500612, -0.64120946],
       [-5.59727174, -0.4476471 ],
       [-2.96127901, -0.39822068],
       [-3.20511285, -0.14391112]])

### Let's create a new user who rated fighting1 5 stars, but gave puppies1 one star. Our rec sys should recommend fighting2 and fighting3, and not recommend puppies2 and puppies3

In [8]:
df = pd.DataFrame(df_matrix)

In [9]:
row = pd.Series([5, 0, 0, 1, 0, 0], index=df.columns)
df = df.append(row, ignore_index=True)
df

      0    1    2    3    4    5
0   0.0  5.0  5.0  0.0  0.0  1.0
1   5.0  0.0  4.0  0.0  1.0  0.0
2   4.0  0.0  5.0  0.0  0.0  0.0
3   5.0  0.0  5.0  0.0  0.0  0.0
4   4.0  5.0  0.0  0.0  0.0  0.0
5   0.0  4.0  0.0  0.0  0.0  0.0
6   0.0  0.0  0.0  4.0  4.0  0.0
7   0.0  0.0  0.0  0.0  5.0  4.0
8   0.0  0.0  0.0  5.0  0.0  5.0
9   0.0  0.0  0.0  0.0  5.0  0.0
10  0.0  0.0  0.0  5.0  0.0  0.0
11  5.0  0.0  0.0  1.0  0.0  0.0

In [31]:
df
dfm = df.as_matrix()
dfm_mean = np.mean(dfm,axis=1)
print dfm_mean
print dfm

[ 1.83333333  1.66666667  1.5         1.66666667  1.5         0.66666667
  1.33333333  1.5         1.66666667  0.83333333  0.83333333  1.        ]
[[ 0.  5.  5.  0.  0.  1.]
 [ 5.  0.  4.  0.  1.  0.]
 [ 4.  0.  5.  0.  0.  0.]
 [ 5.  0.  5.  0.  0.  0.]
 [ 4.  5.  0.  0.  0.  0.]
 [ 0.  4.  0.  0.  0.  0.]
 [ 0.  0.  0.  4.  4.  0.]
 [ 0.  0.  0.  0.  5.  4.]
 [ 0.  0.  0.  5.  0.  5.]
 [ 0.  0.  0.  0.  5.  0.]
 [ 0.  0.  0.  5.  0.  0.]
 [ 5.  0.  0.  1.  0.  0.]]

In [11]:
df_matrix = df.as_matrix()
#df_matrix.asfp
df_matrix = df_matrix.astype(float)



U, sigma1, Vt = svds(df_matrix, k = 2)
sigma = np.diag(sigma1)
print 'here is our user:concept matrix'
print U
print 'concept:concept matrix'
print sigma
print 'game : concept matrix'
print Vt

here is our user:concept matrix
[[ 0.0060226   0.35227369]
 [ 0.00792951  0.46687716]
 [ 0.06755498  0.45606705]
 [ 0.07473123  0.50956589]
 [ 0.04354105  0.31989504]
 [ 0.01186883  0.08471976]
 [-0.49446346  0.04023747]
 [-0.4858123   0.04583716]
 [-0.56123772  0.04318013]
 [-0.29515866  0.02862807]
 [-0.32292067  0.02166877]
 [-0.02870287  0.27182792]]
concept:concept matrix
[[  9.97592123   0.        ]
 [  0.          13.21667516]]
game : concept matrix
[[ 0.07158973  0.02960063  0.07751285 -0.64428623 -0.5888959  -0.47548643]
 [ 0.70707671  0.2799284   0.63987665  0.05727782  0.07567359  0.05686173]]

### Looking at user:concept matrix.

concept1, the left column, and concept2, the right column. We expect the first 5 users to have strong corrospondence to one of the concepts

Observe that the first 5 users all have high absolute values on concept2. And low abs val on concept 1. indicating high correspondence to concept2 (i.e, fighting fans like fighting games.)

users 6-10 have high absolute vals on concept1. and low absolute vals on concept2. (puppies fans like puppies games, as indicated by high absolute vals on concept1)

### Now, dot product our U, sigma, and Vt. Should form our preds matrix

In [12]:
dotUsigma = np.dot(U, sigma)
preds = np.dot(dotUsigma, Vt)
preds

array([[  3.29637041e+00,   1.30509341e+00,   2.98385037e+00,
          2.27969677e-01,   3.16946204e-01,   2.36174066e-01],
       [  4.36872494e+00,   1.72965755e+00,   3.95453120e+00,
          3.02470699e-01,   4.20364570e-01,   3.13255950e-01],
       [  4.31028524e+00,   1.70727018e+00,   3.90921581e+00,
         -8.89464972e-02,   5.92663234e-02,   2.23035303e-02],
       [  4.81536781e+00,   1.90732013e+00,   4.36720681e+00,
         -9.45709624e-02,   7.06144566e-02,   2.84691882e-02],
       [  3.02058002e+00,   1.19638034e+00,   2.73903436e+00,
         -3.76858235e-02,   6.41500047e-02,   3.38751943e-02],
       [  8.00199810e-01,   3.16944423e-01,   7.25656297e-01,
         -1.21503701e-02,   1.50059776e-02,   7.37005017e-03],
       [  2.28946718e-02,   2.85560750e-03,  -4.20598765e-02,
          3.20854970e+00,   2.94510722e+00,   2.37568487e+00],
       [  8.14032974e-02,   2.61275222e-02,   1.19865097e-02,
          3.15718478e+00,   2.89988412e+00,   2.33885713e+00],
       [  2.70596346e-03,  -5.97539995e-03,  -6.88077377e-02,
          3.63995883e+00,   3.34033438e+00,   2.69463440e+00],
       [  5.67406658e-02,   1.87574720e-02,   1.38737908e-02,
          1.91875967e+00,   1.76262436e+00,   1.42157471e+00],
       [ -2.81223260e-02,  -1.51879627e-02,  -6.64486364e-02,
          2.09192745e+00,   1.91875967e+00,   1.54803138e+00],
       [  2.51978835e+00,   9.97212170e-01,   2.27666526e+00,
          3.90263165e-01,   4.40492600e-01,   3.40434565e-01]])

In [13]:
np.set_printoptions(suppress=True)

### Observe the last usr. The predictions matrix predicts that he will likes fighting1, fighting2, fighting3 the most. Success!

### But in this case, we had 2 very obvious genres in our dataset, hence we know to put k=2. What happens for larger datasets? What should be our k-value? From research, best k seems to fall between 20 - 90


Make copy of df called df_copy.

for df_copy, choose 3 of the users. Remove some of their ratings.

Do SVD on this removed r_df_copy

Grab the results of "the chosen", compare to original r_df. compute RMSE

In [14]:
df

      0    1    2    3    4    5
0   0.0  5.0  5.0  0.0  0.0  1.0
1   5.0  0.0  4.0  0.0  1.0  0.0
2   4.0  0.0  5.0  0.0  0.0  0.0
3   5.0  0.0  5.0  0.0  0.0  0.0
4   4.0  5.0  0.0  0.0  0.0  0.0
5   0.0  4.0  0.0  0.0  0.0  0.0
6   0.0  0.0  0.0  4.0  4.0  0.0
7   0.0  0.0  0.0  0.0  5.0  4.0
8   0.0  0.0  0.0  5.0  0.0  5.0
9   0.0  0.0  0.0  0.0  5.0  0.0
10  0.0  0.0  0.0  5.0  0.0  0.0
11  5.0  0.0  0.0  1.0  0.0  0.0

In [15]:

def create_tester(dataframe, k): 
    '''Given our ratings dataframe, select the first k rows, and transform 50% of the values to 0. We now have a 
    ratings dataframe with some hidden values, and we can perform recommendations on it, to compare with our,
    ground truth ratings dataframe.
    Arguments
    dataframe: input your ratings dataframe, where rows are users, columns are items.
    k: number of rows to slice off. These rows will then have some of their values hidden.
    '''
    
    #Create array of the first K rows
    temp_array = np.array(dataframe.iloc[0:k])
    #Change 50% of the values to 0.
    for index in np.nditer(temp_array, op_flags=['readwrite']):
        chance = np.random.randint(1,3) 
        if chance == 1:
            index[...] = 0 
    
    #Return a dataframe that has been modified by 'hiding' ratings, now ready to perform testing. 
    temp_df = pd.DataFrame(temp_array)
    result = temp_df.append(dataframe.drop(dataframe.index[:k], axis=0))
    return result

In [16]:
tester_matrix = create_tester(df, 5)

In [17]:
tester_matrix

      0    1    2    3    4    5
0   0.0  0.0  5.0  0.0  0.0  0.0
1   5.0  0.0  4.0  0.0  1.0  0.0
2   4.0  0.0  5.0  0.0  0.0  0.0
3   5.0  0.0  0.0  0.0  0.0  0.0
4   0.0  5.0  0.0  0.0  0.0  0.0
5   0.0  4.0  0.0  0.0  0.0  0.0
6   0.0  0.0  0.0  4.0  4.0  0.0
7   0.0  0.0  0.0  0.0  5.0  4.0
8   0.0  0.0  0.0  5.0  0.0  5.0
9   0.0  0.0  0.0  0.0  5.0  0.0
10  0.0  0.0  0.0  5.0  0.0  0.0
11  5.0  0.0  0.0  1.0  0.0  0.0

In [18]:
tester_matrix

      0    1    2    3    4    5
0   0.0  0.0  5.0  0.0  0.0  0.0
1   5.0  0.0  4.0  0.0  1.0  0.0
2   4.0  0.0  5.0  0.0  0.0  0.0
3   5.0  0.0  0.0  0.0  0.0  0.0
4   0.0  5.0  0.0  0.0  0.0  0.0
5   0.0  4.0  0.0  0.0  0.0  0.0
6   0.0  0.0  0.0  4.0  4.0  0.0
7   0.0  0.0  0.0  0.0  5.0  4.0
8   0.0  0.0  0.0  5.0  0.0  5.0
9   0.0  0.0  0.0  0.0  5.0  0.0
10  0.0  0.0  0.0  5.0  0.0  0.0
11  5.0  0.0  0.0  1.0  0.0  0.0

In [19]:
#Perform svd on tester_matrix

df_matrix = tester_matrix.as_matrix()
#df_matrix.asfp
df_matrix = df_matrix.astype(float)

U, sigma1, Vt = svds(df_matrix, k = 2)
sigma = np.diag(sigma1)
print 'here is our user:concept matrix'
print U
print 'concept:concept matrix'
print sigma
print 'game : concept matrix'
print Vt

dotUsigma = np.dot(U, sigma)
preds = np.dot(dotUsigma, Vt)
preds

here is our user:concept matrix
[[ 0.09388943  0.25491863]
 [ 0.12288932  0.57256878]
 [ 0.17727104  0.53557686]
 [ 0.10422701  0.35082279]
 [-0.         -0.        ]
 [-0.         -0.        ]
 [-0.47782894  0.13363573]
 [-0.4707583   0.12570146]
 [-0.55068022  0.12379675]
 [-0.28224615  0.08905544]
 [-0.31504003  0.07798922]
 [ 0.041219    0.36642064]]
concept:concept matrix
[[  9.91864559   0.        ]
 [  0.          11.06553143]]
game : concept matrix
[[ 0.20675815 -0.          0.1862512  -0.62495408 -0.5598999  -0.46744631]
 [ 0.77640813 -0.          0.56416202  0.17259843  0.19708915  0.10137693]]

array([[ 2.38264467, -0.        ,  1.76484149, -0.09512483,  0.03454093,
        -0.14934712],
       [ 5.17116603, -0.        ,  3.80142605,  0.33179152,  0.56625352,
         0.07253342],
       [ 4.9648787 , -0.        ,  3.67095723, -0.07595492,  0.18357193,
        -0.22110098],
       [ 3.22779255, -0.        ,  2.38264467,  0.02396238,  0.18628875,
        -0.08969232],
       [-0.        ,  0.        , -0.        , -0.        , -0.        ,
         0.        ],
       [-0.        ,  0.        , -0.        , -0.        , -0.        ,
         0.        ],
       [ 0.1682009 , -0.        , -0.04846712,  3.2171473 ,  2.94504416,
         2.36533367],
       [ 0.11453489, -0.        , -0.08493677,  3.15816495,  2.88847392,
         2.32365054],
       [-0.06572994,  0.        , -0.24447195,  3.649939  ,  3.32816222,
         2.69206659],
       [ 0.18628875, -0.        ,  0.03454093,  1.91964503,  1.76166017,
         1.40851719],
       [ 0.02396238, -0.        , -0.09512483,  2.1017891 ,  1.91964503,
         1.5481499 ],
       [ 3.23258502, -0.        ,  2.3636197 ,  0.4443202 ,  0.57021775,
         0.21993766]])

In [20]:
print preds
print df
print preds - np.array(df) #This is the difference.

[[ 2.38264467 -0.          1.76484149 -0.09512483  0.03454093 -0.14934712]
 [ 5.17116603 -0.          3.80142605  0.33179152  0.56625352  0.07253342]
 [ 4.9648787  -0.          3.67095723 -0.07595492  0.18357193 -0.22110098]
 [ 3.22779255 -0.          2.38264467  0.02396238  0.18628875 -0.08969232]
 [-0.          0.         -0.         -0.         -0.          0.        ]
 [-0.          0.         -0.         -0.         -0.          0.        ]
 [ 0.1682009  -0.         -0.04846712  3.2171473   2.94504416  2.36533367]
 [ 0.11453489 -0.         -0.08493677  3.15816495  2.88847392  2.32365054]
 [-0.06572994  0.         -0.24447195  3.649939    3.32816222  2.69206659]
 [ 0.18628875 -0.          0.03454093  1.91964503  1.76166017  1.40851719]
 [ 0.02396238 -0.         -0.09512483  2.1017891   1.91964503  1.5481499 ]
 [ 3.23258502 -0.          2.3636197   0.4443202   0.57021775  0.21993766]]
      0    1    2    3    4    5
0   0.0  5.0  5.0  0.0  0.0  1.0
1   5.0  0.0  4.0  0.0  1.0  0.0
2   4.0  0.0  5.0  0.0  0.0  0.0
3   5.0  0.0  5.0  0.0  0.0  0.0
4   4.0  5.0  0.0  0.0  0.0  0.0
5   0.0  4.0  0.0  0.0  0.0  0.0
6   0.0  0.0  0.0  4.0  4.0  0.0
7   0.0  0.0  0.0  0.0  5.0  4.0
8   0.0  0.0  0.0  5.0  0.0  5.0
9   0.0  0.0  0.0  0.0  5.0  0.0
10  0.0  0.0  0.0  5.0  0.0  0.0
11  5.0  0.0  0.0  1.0  0.0  0.0
[[ 2.38264467 -5.         -3.23515851 -0.09512483  0.03454093 -1.14934712]
 [ 0.17116603 -0.         -0.19857395  0.33179152 -0.43374648  0.07253342]
 [ 0.9648787  -0.         -1.32904277 -0.07595492  0.18357193 -0.22110098]
 [-1.77220745 -0.         -2.61735533  0.02396238  0.18628875 -0.08969232]
 [-4.         -5.         -0.         -0.         -0.          0.        ]
 [-0.         -4.         -0.         -0.         -0.          0.        ]
 [ 0.1682009  -0.         -0.04846712 -0.7828527  -1.05495584  2.36533367]
 [ 0.11453489 -0.         -0.08493677  3.15816495 -2.11152608 -1.67634946]
 [-0.06572994  0.         -0.24447195 -1.350061    3.32816222 -2.30793341]
 [ 0.18628875 -0.          0.03454093  1.91964503 -3.23833983  1.40851719]
 [ 0.02396238 -0.         -0.09512483 -2.8982109   1.91964503  1.5481499 ]
 [-1.76741498 -0.          2.3636197  -0.5556798   0.57021775  0.21993766]]

In [21]:
def rmse(test_df, prediction):
    np.sqrt(sum(sum((prediction - np.array(test_df)) ** 2)) / (preds.shape[0] * preds.shape[1]))